name: Build and Run Docker
description: Build and Run Docker images
inputs:
  image_name:
    description: 'Docker image name'
    required: true
  run_container:
    description: 'Should the docker container be executed?'
    required: false
    default: 'true'
  dockerfile:
    description: 'Name of the Dockerfile'
    required: false
    default: 'Dockerfile'
runs:
  using: composite
  steps:
    - name: Set up Docker Engine
      uses: docker/setup-buildx-action@v3

    - name: Build docker image
      run: docker build -f ${{inputs.Dockerfile}} -t ${{inputs.image_name}} .
      shell: bash

    - name: Run Docker container
      if: ${{inputs.run_container == 'true'}}
      run: docker run --rm ${{inputs.image_name}}
      shell: bash