
name: CI
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build with Gradle
        run: gradle build

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        run: ls